### ISSUE TITLE
Version 1.8.11 Debian bulseyes

### ISSUE THREAD

**Issue by michel-thomas** [chriswayg/ansible-msmtp-mailer#10]
New Debian version 11 (bulseyes) includes a `msmtp` upgrade to version 1.8.11 (Debian 10 buster has 1.8.3 by default).

This new version (since 1.8.8) allows to replace `From:` header with `set_from_header on` parameter.

Could you please include this parameter in config?

Many thanks

**Comment by markstos** [comment]
This can be closed  as dupe of #11 which is a PR proposing to implement this.

**Comment by michel-thomas** [comment]
Yes, sure!
