### ISSUE TITLE
Update code on Galaxy

### ISSUE THREAD

**Issue by colans** [chriswayg/ansible-msmtp-mailer#9]
@chriswayg Thanks for getting those PRs in, notably https://github.com/chriswayg/ansible-msmtp-mailer/pull/5.  Would you kindly do an import on [Galaxy](https://galaxy.ansible.com/chriswayg/msmtp-mailer) to update the code there?

> Last Commit: 2 years ago\
> Last Import: 2 years ago 

I'm trying to unfork now that PRs have been merged and use your role directly from Galaxy, without having to submodule the repo.  Thanks!

**Comment by markstos** [comment]
I believe I installed from Galaxy and see the changes from #5 in my local copy, despite the Galaxy website saying the Last Import was 4 years ago. @colans could you confirm that using `ansible-galaxy install` does /not/ reflect these changes?

**Comment by colans** [comment]
@markstos Confirmed!  The changes *are* there for me.  So I guess that's a bug on the site then?
